### ISSUE TITLE
No multi-platform-build image available to run it on a Pi?

### ISSUE THREAD

**Issue by tackin** [KIMB-technologies/Radio-API#10]
Hi!

Not sure if it is appropriate to open this as an issue. Please just close it if I'm wrong.
Tried to run the container on a Raspi 4.

I run into a docker-compose error:
radio_api The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 

And later this may have lead to the following error:
exec /usr/local/bin/docker-php-entrypoint: exec format error

It would be absolutely great to have a docker-container for a Raspberry Pi to run it in my the local home-network.

btw: I tried to build an image from the repo on my RaspberryPi today which failed also redis-related.

**Comment by jeglinski** [comment]
Hi Heinz,

@kimbtech has only provided docker images for "linux/amd64" at https://hub.docker.com/r/kimbtechnologies/radio_api/tags.

You have to build a Docker image for your platform "linux/arm64/v8" yourself.

Take the e.g. the file https://github.com/KIMB-technologies/Radio-API/blob/d5dbe02fc23ad75be8899d4fb80dc046f10f5420/docker-compose.dev.yml and run it with docker compose.

The result is a local Docker image for your platform. 
Thomas

@kimbtech: thanks your sharing your code. It´s now particularly important to have a good alternative to the "Frontier radio portal", 
especially after this announcement: https://subscriptions.frontier-nuvola.net/portal/en/home

**Comment by tackin** [comment]
> You have to build a Docker image for your platform "linux/arm64/v8" yourself.
> 
> Take the e.g. the file https://github.com/KIMB-technologies/Radio-API/blob/d5dbe02fc23ad75be8899d4fb80dc046f10f5420/docker-compose.dev.yml and run it with docker compose.
> 
> The result is a local Docker image for your platform. Thomas

Hi!
Well as I mentioned, the build will fail on arm64. Reasons are multiple:
"FROM" image is not multi-platform as well
pecl not available anymore by default

It's beyond my docker-skills to fix that to make it run.

**Comment by kimbtech** [comment]
Hi,  
unfortunately the Radio-API-Image builds on top of the [PHP-NGINX-Docker](https://github.com/KIMB-technologies/PHP-NGINX-Docker)-Image. Both are only available for AMD64 and not ARM which is used by Raspberry Pis.

I do not have a Raspberry Pi to test or run the build process on. In addition, as far as I can see, Github Actions (currently used to automatically build the images), does not provide support for ARM either.  
Thus, I can't provide an image for Raspberry Pis.

You might try to build [PHP-NGINX-Docker](https://github.com/KIMB-technologies/PHP-NGINX-Docker) first and afterwards build the image of Radio-API as described above.
I do not get any errors about PECL.

Maybe I'll take a closer look at https://github.com/docker/setup-buildx-action at some point. It may offer a way to create ARM images via Github actions.

**Comment by tackin** [comment]
> You might try to build [PHP-NGINX-Docker](https://github.com/KIMB-technologies/PHP-NGINX-Docker) first and afterwards build the image of Radio-API as described above. I do not get any errors about PECL.

I used: https://hub.docker.com/r/trafex/php-nginx
in dockerfile:

FROM trafex/php-nginx

and need to insert

USER root
root@raspi4:/home/pi/work/Radio-API# docker compose up
root@raspi4:/home/pi/work/Radio-API# docker compose up
[+] Building 2.2s (6/10)                                                                                                                                                 docker:default
 => [radio_api internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                    0.0s
 => [radio_api internal] load build definition from Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 503B                                                                                                                                               0.0s
 => [radio_api internal] load metadata for docker.io/trafex/php-nginx:latest                                                                                                       0.5s
 => CACHED [radio_api 1/6] FROM docker.io/trafex/php-nginx@sha256:243228b3d7373ea2135e9b18e8b3dd74f1ee843d437ddc3aa81fb5f1af1deed8                                                 0.0s
 => [radio_api internal] load build context                                                                                                                                        0.0s
 => => transferring context: 2.06kB                                                                                                                                                0.0s
 => ERROR [radio_api 2/6] RUN apk add --update --no-cache $PHPIZE_DEPS  && pecl install redis  && docker-php-ext-enable redis                                                      1.7s
------
 > [radio_api 2/6] RUN apk add --update --no-cache $PHPIZE_DEPS         && pecl install redis   && docker-php-ext-enable redis:
0.471 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
0.746 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
1.495 OK: 123 MiB in 96 packages
1.689 /bin/sh: pecl: not found
------
WARN[0000] buildx: failed to read current commit information with git rev-parse --is-inside-work-tree
failed to solve: process "/bin/sh -c apk add --update --no-cache $PHPIZE_DEPS \t&& pecl install redis \t&& docker-php-ext-enable redis" did not complete successfully: exit code: 127
root@raspi4:/home/pi/work/Radio-API#

**Comment by kimbtech** [comment]
Hi,  
it looks like you use the image `trafex/php-nginx` as baseimage. This image will not be compatible to Radio-API as Radio-API sets the configurations for https://github.com/KIMB-technologies/PHP-NGINX-Docker.

**Comment by tackin** [comment]
Ahhhhgrrrrr!!!! 
Thank you very much for the hint. Great!
It's now up and running.

**Comment by tackin** [comment]
btw: 
I added a mcavlan-config with an own local IP to my docker-compose of Radio-API for this container-network.
Now I can expose Port 80 multiple times on my docker-host and only have to redirect Frontier-DNS-requests to that new Docker-network-IP in the local net.

**Comment by kimbtech** [comment]
I opened an issue regarding multi plattform builds: https://github.com/KIMB-technologies/Radio-API/issues/13
