### ISSUE TITLE
DUAL IR6 - Radio not supported

### ISSUE THREAD

**Issue by tackin** [KIMB-technologies/Radio-API#11]
After bringing the Radio-API container finally up on my Raspi4 I tested it with my Dual IR6. It did not work and the radio could not connect to a stream. I guess the communication with frontier is a bit different on that device.
I made a TCP-Dump on the router filtered by the Radios MAC-address while the Radio powers up and connects to Frontier to dive into it.
I can provide this Dump to investigate whats going on and how you probably could adapt to this (and other) Radios in the code as well.
Someone interested?

**Comment by kimbtech** [comment]
Hi,

I have a reposition https://github.com/kimbtech/WiFi-RadioAPI/blob/master/HamaAPI.md where I added some of the requests and answers my radio produces.
It might be interesting to compare the differences to the Dual radio.

So yes, I would be interested. However I can not promise to make Radio-API work with the other radio.

**Comment by tackin** [comment]
Where/how would you like me to provide the dump?

After all I'm still not sure if Dual IR6 is even affected by the frontier-changes as it stores the facorites local on the radio and may therefore just keeping requesting for the stream-uri and keeps getting that answered from frontier without account.
But if not, it would be nice to be able to switch to Radio-API.

**Comment by tackin** [comment]
I put it here for you:
https://nextcloud.digilay.duckdns.org/s/TSZrt5NASJWqiNi

**Comment by kimbtech** [comment]
Thanks, I downloaded the file.

**Comment by kimbtech** [comment]
Hi,

I checked the tcp dumps. The requests seem to be very similar to the ones of my radio. However, yours has the value `dual` for `CONF_SETUPAPP_IDENT`. May this be the cause of the problems?

I released a new version, which does not need to set  `CONF_SETUPAPP_IDENT` anymore, see [v2.3.12](https://github.com/KIMB-technologies/Radio-API/releases/tag/v2.3.12).

**Comment by kimbtech** [comment]
I just added ARM versions of the Docker Images to Docker Hub. I can't test them on a Raspberry Pi, but they will hopefully run.

**Comment by tackin** [comment]
I will test and report you tomorrow.Am 06.11.2023 20:25 schrieb KIMBtech ***@***.***>:
I just added ARM versions of the Docker Images to Docker Hub. I can't test them on a Raspberry Pi, but they will hopefully run.

**Comment by tackin** [comment]
Confirm! The image runs on arm64.
Raspi4 Debian GNU/Linux 11 (bullseye)

**Comment by kimbtech** [comment]
Hi,

thats quite interesting. I do not get JSON responses and but get XML responses.

My radio sends similar requests and when I do the following request via my computer to `wifiradiofrontier.com` I get:

`curl -v http://dual.wifiradiofrontier.com/setupapp/dual/asp/BrowseXML/loginXML.asp?gofile=&mac=xxxxxxx&dlang=eng&fver=4&ven=dual12`

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ListOfItems>
  <ItemCount>-1</ItemCount>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>My Favourites</Title>
    <UrlDir>http://shim-pri.wifiradiofrontier.com/vtuner/radios/favorites?</UrlDir>
    <UrlDirBackUp>http://shim-sec.wifiradiofrontier.com/vtuner/radios/favorites?</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Local Germany</Title>
    <UrlDir>http://shim-pri.wifiradiofrontier.com/vtuner/radios/country/8777677923440934?</UrlDir>
    <UrlDirBackUp>http://shim-sec.wifiradiofrontier.com/vtuner/radios/country/8777677923440934?</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Stations</Title>
    <UrlDir>http://shim-pri.wifiradiofrontier.com/vtuner/radios?</UrlDir>
    <UrlDirBackUp>http://shim-sec.wifiradiofrontier.com/vtuner/radios?</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Podcasts</Title>
    <UrlDir>http://shim-pri.wifiradiofrontier.com/vtuner/feeds?</UrlDir>
    <UrlDirBackUp>http://shim-sec.wifiradiofrontier.com/vtuner/feeds?</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>My added Stations</Title>
    <UrlDir>http://shim-pri.wifiradiofrontier.com/vtuner/streams/favorites?</UrlDir>
    <UrlDirBackUp>http://shim-sec.wifiradiofrontier.com/vtuner/streams/favorites?</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Help</Title>
    <UrlDir>http://shim-pri.wifiradiofrontier.com/vtuner/help?</UrlDir>
    <UrlDirBackUp>http://shim-sec.wifiradiofrontier.com/vtuner/help?</UrlDirBackUp>
  </Item>
</ListOfItems>
```

When I run a similar request to Radio-API, I get this similar and corresponding answer:

`curl -v "http://radio.example.com/setupapp/dual/asp/BrowseXML/loginXML.asp?gofile=&mac=xxxxxxx&dlang=eng&fver=4&ven=dual12"`

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ListOfItems>
  <ItemCount>4</ItemCount>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Podcast</Title>
    <UrlDir>http://radio.example.com/cat?cid=3</UrlDir>
    <UrlDirBackUp>http://radio.example.com/cat?cid=3</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Radio</Title>
    <UrlDir>http://radio.example.com/cat?cid=1</UrlDir>
    <UrlDirBackUp>http://radio.example.com/cat?cid=1</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Stream</Title>
    <UrlDir>http://radio.example.com/cat?cid=2</UrlDir>
    <UrlDirBackUp>http://radio.example.com/cat?cid=2</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>GUI-Code: Zxxxx</Title>
    <UrlDir>http://radio.example.com/?go=initial</UrlDir>
    <UrlDirBackUp>http://radio.example.com/?go=initial</UrlDirBackUp>
  </Item>
</ListOfItems>
```

Just as hint: As far as I know, the value `mac=` in the urls is your personal token/ key. So you can may want to omit it here.

**Comment by tackin** [comment]
Also if you use an IP?
Like
Http://192.198.0.99/..... instead of http://radio.example.com/...  ?

**Comment by tackin** [comment]
Also if you use an IP?
Like
Http://192.198.0.99/..... instead of http://radio.example.com/...  ?

The mac above is just random build for demo. ;-)

**Comment by kimbtech** [comment]
I just tested it locally (Docker container running on my computer in the local network with port 80 open). 
There it works the way it should, e.g., with:
`curl -v "http://192.168.0.99/setupapp/dual/asp/BrowseXML/loginXML.asp?gofile=&mac=fe9971bad537ca2b9820107a7dc41b73&dlang=eng&fver=4&ven=dual12"`

If the API sends empty responses it might be an problem/ error with PHP or messages by PHP
Error messages are only shown when setting `DEV=dev` in the environment via docker-compose.

Does the web interface at `http://192.168.0.99/gui/` work?

**Comment by tackin** [comment]
Yes I get the page where I can put in my login-code.
But the login with a code from table.json  than leads again to an empty page.

**Comment by tackin** [comment]
Warning: Trying to access array offset on value of type null in /php-code/classes/Id.php on line 107

Fatal error: Uncaught TypeError: RedisCache::arraySet(): Argument #2 ($array) must be of type array, null given, called in /php-code/classes/Id.php on line 107 and defined in /php-code/classes/RedisCache.php:153 Stack trace: #0 /php-code/classes/Id.php(107): RedisCache->arraySet('macs', NULL) #1 /php-code/classes/Id.php(43): Id->loadFileIntoRedis(Object(RedisCache)) #2 /php-code/classes/Login.php(47): Id->__construct('ZUVqp', 3) #3 /php-code/gui/index.php(28): Login->loginByCode('ZUVqp') #4 {main} thrown in /php-code/classes/RedisCache.php on line 153

**Comment by tackin** [comment]
I run 2 networks in that Radio-API container.
1. mcvlan with an IP of my net  (no ports exposed because not needed)
2. default with a usual internal docker-bridge (no ports exposed as also not needed) to connect redis and Radio-API.

I get no log-errors in the container on startup. So redis should work fine.

**Comment by kimbtech** [comment]
It looks as there is a problem with the `table.json`. It may contain a syntax error or similar, because currently PHP ist not able to parse it and thus uses a null value.

If your `table.json` does not contain any valuably information you may delete it and Radio-API will create a new one (when the radio connects).

**Comment by tackin** [comment]
Ok I tested it.
1. delete old table.json
2. request http://192.168.0.123/setupapp/dual/asp/BrowseXML/loginXML.asp?gofile=&mac=xxxxxxx&dlang=eng&fver=4&ven=dual12
3. Radio-API bulids new table
4. Look into the table.json to read    
```
},
    "codes": {
        "Zw6vs": 1
    }
```
5. request http://192.168.0.123/gui
6. insert Login-code: Zw6vs
7. get back:
`Fatal error: Uncaught TypeError: Data::addCategoryToTable(): Argument #2 ($data) must be of type array, null given, called in /php-code/classes/Data.php on line 91 and defined in /php-code/classes/Data.php:108 Stack trace: #0 /php-code/classes/Data.php(91): Data->addCategoryToTable(1, NULL) #1 /php-code/classes/Data.php(34): Data->constructTable() #2 /php-code/classes/Inner.php(23): Data->__construct(1) #3 /php-code/gui/index.php(42): Inner->__construct(1) #4 {main} thrown in /php-code/classes/Data.php on line 108
`

**Comment by tackin** [comment]
found it:
table.json was ok but radio_1.json was brocken.
