### ISSUE TITLE
Radio Station Database

### ISSUE THREAD

**Issue by kimbtech** [KIMB-technologies/Radio-API#14]
Integrate a list of radio stations via the API of https://www.radio-browser.info/
There are two possibilities to do this:

1. Add a feature to search the list of stations in the web gui of Radio-API. Thus, it is not necessary to manually get the streaming urls of radio stations. (The display in the radio stays unchanged.)
2. Add stations from „Radio-Browser“ to the items displayed by the radio (as a new folder/ category). Possibly add a search etc.

**Comment by tackin** [comment]
For "1." I would like to refere to an other image addressing the same issue with "vtuner" a view years ago.
 https://hub.docker.com/r/mpvd/vtuner-emulator-ycast
 https://github.com/mpvd/vTuner-Emulator-YCast/

**Comment by tackin** [comment]
This API (all.api.radio-browser.info) is used/called by that local vtuner-emulator-ycast:
http://all.api.radio-browser.info/json/tags?hidebroken=true
or with xml-answer:
http://all.api.radio-browser.info/xml/tags?hidebroken=true

It's open source.
https://www.radio-browser.info/

**Comment by kimbtech** [comment]
I plan to implement 1. and 2. using Radio-Browser. Then Radio-API will be completely independent of Frontier Silicon‘s service and based on an Open Source solution.

However, implementing the features will take some time.
