### ISSUE TITLE
Display Version at GUI

### ISSUE THREAD

**Issue by stoneubi** [KIMB-technologies/Radio-API#24]
It would be nice to have the installed Version displayed at the GUI. E.g. installed version is 2.5. 

It would also be even better to see at the same page that an new version is available. 

Thank you very much for your effort and very good radio api. 

I also found out that my Hama IR 100 as an option at system configuration that the radio will be still connected to the lan / wifi even at standby modus. Once activated the reload / restart after the wakeup from standby will be 10 times faster.

Thx you, 
Stoneubi

**Comment by kimbtech** [comment]
I added a version hin to the footer of each webpage and *Radio-API* will show a banner if a newer version (i.e., git tag) exists (it checks approx. all three days).

**Comment by stoneubi** [comment]
Wow, that was fast. Thank you so much 😃👍
