### ISSUE TITLE
Organise in Folders 

### ISSUE THREAD

**Issue by kimbtech** [KIMB-technologies/Radio-API#31]
Thanks I made it I would have a wish could you possibly create more folders for eg xmas, 80s, 90s thanks in advance and best regards

_Originally posted by @Sepphuber007 in https://github.com/KIMB-technologies/Radio-API/issues/7#issuecomment-1838856283_

**Comment by kimbtech** [comment]
Hi!

I moved your comment over here to a new issue because it covers a new idea and is not part of #7.

What do you exactly mean by create folders?

To be able to group the radio stations and podcasts added in the web interface in different folders, i.e., the radio would then show something like this:

```text
Radio
├── Folder "90s"
│   ├── Station "90s Hits"
│   ├── Station "Best of 90s"
│   └── ... etc.
├── Folder "Xmas"
│   ├── Station "Merry XMas"
│   └── Station "XMas Hits"
└── ... etc.
```

**Comment by Sepphuber007** [comment]
Is that exactly what the next update will do?
Would be great thanks

Best regards

**Comment by kimbtech** [comment]
Currently, I do not have a fixed plan/ schedule for the next version. 
Adding the folders is a bit more work to do, so I will need some time.
But I think it is a relevant feature to add to Radio-API, thus I put i on my list.

(However, if somebody has another feature or idea which is fast to implement, I might do the other one first.)

**Comment by Sepphuber007** [comment]
Thank you, I would be happy if it is implemented

Many thanks in advance

**Comment by Sepphuber007** [comment]
Thanks for the quick implementation

**Comment by Sepphuber007** [comment]
Hello

The Category cannot be changed or deleted 
My daughter has created a Category by mistake. How can I delete it?
Is it necessary for you to Change the source code? 

Thanks again in advance

and best regards

**Comment by kimbtech** [comment]
Hi,
just make sure that the category to delete is assigned with no radio station or podcast. Radio-API will delete empty categories.

**Comment by Sepphuber007** [comment]
Thanks for the quick reply, I will give it a try

and best regards
