### ISSUE TITLE
Any further intention in making the API even more interesting for the "international" audience?

### ISSUE THREAD

**Issue by tackin** [KIMB-technologies/Radio-API#33]
... i.e. by adding a language-file-system with english translations for all german pagetexts as autotranslation is still not "the yellow of the egg" for those who are not that familiar with german. ;-)

**Comment by tackin** [comment]
Oh, missed the fact that in classes are all templates in EN as well.

**Comment by kimbtech** [comment]
Exactly, Radio-API detects your browser's language headers and automatically select between German and English (English is the fallback for unsupported languages). 

Recently I also added support for different language in the radio's display, i.e., Radio-API respects the `dlang=ger` or `dlang=eng` parameters.
