### ISSUE TITLE
Setup Test Program

### ISSUE THREAD

**Issue by kimbtech** [KIMB-technologies/Radio-API#35]
Sometimes it is a bit fiddely to set up Radio-API (DNS queries, server names, ...).

Thus, it could be helpful to provide a tester application. The application should be a multi platform executable. Then, this  executable can be run on a computer in the same network the radio is in and the executable will check the setup 
 and connection and give hints about all problems and possible error causes.

Implement this (possibly using GoLang) and provide the executables for Linux, MacOS, Windows.

**Comment by Demel75** [comment]
:-) Great job. Works like a charm. Thanx

**Comment by kimbtech** [comment]
This is somehow really difficult to realise – a language providing good interfaces for DNS queries and being able to cross-compile for Linux, MacOS, Windows while I need to be able to write code in this language ...

Thus, this idea/ issue will be closed for now.
