### ISSUE TITLE
Question about nextcloud share

### ISSUE THREAD

**Issue by stoneubi** [KIMB-technologies/Radio-API#41]
Hello, I tried to link the radio to the mentioned nextcloud share but without success.

Steps I did:
- I created a nextcloud share without any password protection
- stored some mp3 files there
- opened the radio api gui and created a new radio station with nextcloud checkbox and ssl proxy selected
- at the radio I can see and select the nextcloud share but no music will be played

What did I won't y?

Thank you
stoneubi

**Comment by kimbtech** [comment]
Hi,

your steps seem right to me. Maybe there are some issues for Radio-API connecting to the nextcloud. 

To debug this:
If you add the same nextcloud share as podcast, does the Radio show each mp3 file as an episode? (If yes, we know that Radio-API can correctly fetch the list of files from the nextcloud.)

Is the radio then able to play the episodes, i.e., audio files from the nextcloud podcast? 

Do you use the Proxy via Docker install or the PHP-based proxy (non-Docker install)?

**Comment by stoneubi** [comment]
Sorry for late reply due to holidays.

Situation is still the same even with pidcasts.

Regarding proxy - do I need to use a proxy?

I use my own nextcloud and pihole as my dns proxy with modified settings to re-route the frontier ip adress but to my understanding this should not have any impact on the mentioned nextcloud share. Correct?

If I open the GUI and paste the nextcloud share for a folder containing the mp3 files, nothing will be shown even if proxy is selected.

**Comment by kimbtech** [comment]
Hi,

you might need to use the proxy, if your nextcloud is only accessible via HTTPS. However, this seems not to be the current problem.

So, as you do not get the list of mp3 list when using the nextcloud share as podcast, you may need to change the settings of the nextcloud:
Radio-API uses WebDav to access the files in the share and this is only enabled if the option described in the box at https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html#accessing-public-shares-over-webdav is enabled.

**Comment by stoneubi** [comment]
Thank you. I changed the settings in nextcloud to allow webdav but still same. At podcast on the radio there are no files. 

My settings:
![grafik](https://github.com/KIMB-technologies/Radio-API/assets/32926093/37a3f119-9152-4e61-b6eb-dede14966620)

![grafik](https://github.com/KIMB-technologies/Radio-API/assets/32926093/3e057c9f-9257-43fd-bcf2-d8ba1dbc426a)

Anyhow, I think, I'm doing something wrong. Maybe you have one more tipp for me.

**Comment by stoneubi** [comment]
Sorry, now I understand the documentation about the link. I changed the link and tried it again. The radio does now display the mp3s but cannot play it. It tries it and nothing happens. Now error message. 

Do you have any other suggestions?

Thank you

**Comment by kimbtech** [comment]
Thats good, that the files are listed now. 
I think, I got the problem why the files do not play. I will need to do an update to Radio-API to correctly work with `index.php` in nextcloud shares,

**Comment by kimbtech** [comment]
Hi,  
I just published an update for Radio-API to recognize `index.php` in nextcloud links correctly.

I hope this will fix you issues.
