### ISSUE TITLE
Update own Streams via interval

### ISSUE THREAD

**Issue by rliegmann** [KIMB-technologies/Radio-API#42]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when ...

**Describe the solution you'd like**
Since GRUNDIG discontinued a vtuner service on December 24th, 2023, my Sonoclock radio was completely unusable.
With the pretty cool project here, I was able to get the whole thing up and running again.
Since I like to listen to music streams from Twitch and extract them with other software and make them available locally via the icecast server, I thought that the own streams function was perfect for this.
The own stream json file appears to only be read once at startup. 
Is there an option to read the whole thing at intervals? The background is that these streams are not always online and I would like to only make the streams visible when they are live?

**Additional context**
First of all, none

LG  Ralf

**Comment by kimbtech** [comment]
Hi, 
generally, the own streams are cached for `CONF_CACHE_EXPIRE` seconds, it should default to 1200 seconds. In my installation I use the own streams feature in a very similar use case you describe. If your installer caches the own streams forever this may be a bug.

Do you use the Docker or non-Docker install?
What is the value of `CONF_CACHE_EXPIRE` in your configuration?

**Comment by rliegmann** [comment]
Hi,
i use the Doker version.
By adjusting the `CONF_CACHE_EXPIRE` to e.g. 10 seconds, everything was updated cleanly.
If I had just waited the 20 minutes. :-)
Now I understand the `CONF_CACHE_EXPIRE` too. So not a bug but a feature.
Big thanks for your work.

**Comment by kimbtech** [comment]
Hi,
I am happy to hear that it works now.

And I always assumed I would be the only one using the own streams feature, so nice to know that there are other users.
