### ISSUE TITLE
No GUI interface on the web server. My installation settings are wrong?

### ISSUE THREAD

**Issue by DarioX7** [KIMB-technologies/Radio-API#43]
**Radio-API Installation**
- Version of Radio-API: Version 2.8
- Installation mode: Docker (import docker-compose.yml to CasaOS LXC [PROXMOX])
- DNS redirect via: Adguard Home
- Radio vendor: TechniSat DIGIRADIO-631
- Usage of reverse proxy: no
- Does another radio use your installation of Radio-API: no

**Describe the Issue**  
- No GUI interface on the web server.

**Error Message or Log Files**  

In portainer.io:

> Warning: Redis::pconnect(): php_network_getaddresses: getaddrinfo for redis failed: Name does not resolve in /php-code/classes/RedisCache.php on line 44
> Fatal error: Uncaught RedisException: php_network_getaddresses: getaddrinfo for redis failed: Name does not resolve in /php-code/classes/RedisCache.php:44
> 
> Stack trace:
> #0 /php-code/classes/RedisCache.php(44): Redis->pconnect('redis', 6379)
> #1 /php-code/classes/Cache.php(131): RedisCache->__construct('allowed_domains')
> #2 /php-code/classes/Config.php(250): Cache->__construct('allowed_domains')
> #3 /startup.php(24): Config::parseAllowedDomain(true)
> 
> }
>   thrown in /php-code/classes/RedisCache.php on line 44
> [31-Dec-2023 20:55:01] NOTICE: fpm is running, pid 16
> [31-Dec-2023 20:55:01] NOTICE: ready to handle connections
> 127.0.0.1 -  31/Dec/2023:20:55:22 +0000 "GET /index.php" 200

My settings for docker-compose:

> name: resilient_khalid
> services:
>   radio_api:
>     cpu_shares: 50
>     command: []
>     container_name: radio-api
>     depends_on:
>       redis:
>         condition: service_started
>         required: true
>     deploy:
>       resources:
>         limits:
>           memory: 2048M
>     environment:
>       - CONF_ALLOWED_DOMAIN=all
>       - CONF_CACHE_EXPIRE=1200
>       - CONF_DOMAIN=http://casaos.lan/
>       - CONF_REDIS_HOST=redis
>       - CONF_SHUFFLE_MUSIC=true
>       - CONF_STREAM_JSON=false
>     image: kimbtechnologies/radio_api:latest
>     ports:
>       - target: 80
>         published: "8090"
>         protocol: tcp
>     restart: always
>     volumes:
>       - type: bind
>         source: /DATA/Media/TECHNISAT/data
>         target: /php-code/data
>       - type: bind
>         source: /DATA/Media/TECHNISAT
>         target: /php-code/media
>     devices: []
>     cap_add: []
>     network_mode: bridge
>     privileged: false
>   redis:
>     cpu_shares: 50
>     command: []
>     container_name: radio-api-redis
>     deploy:
>       resources:
>         limits:
>           memory: 2048M
>     image: redis:alpine
>     ports:
>       - target: 6379
>         published: "6379"
>         protocol: tcp
>     restart: always
>     volumes: []
>     devices: []
>     cap_add: []
>     environment: []
>     network_mode: bridge
>     privileged: false
> x-casaos:
>   author: self
>   category: self
>   hostname: casaos.lan
>   icon: ""
>   index: /
>   port_map: "8090"
>   scheme: http
>   store_app_id: resilient_khalid
>   title:
>     custom: technisat

**Comment by DarioX7** [comment]
Problem solved, at the same time I will answer my own question.

You need to select a network called `radio_api` in the docker settings for container `radio-api` and for `radio-api-redis` and set it to public type.

**Comment by kimbtech** [comment]
Hi,
glad to hear that!

The solution matches the error, as it looks like some issue with name resolving for redis and thus the container network.
