### ISSUE TITLE
Uncaught RedisException: Connection refused

### ISSUE THREAD

**Issue by SpeedyGoneZales** [KIMB-technologies/Radio-API#45]
The goal is to run version 2.8.1 as [docker container](https://hub.docker.com/r/kimbtechnologies/radio_api) on a QNAP TS-253 (v 5.1.4.2696) using [Container Station](https://www.qnap.com/en-us/software/container-station) v3.0.5.623 to cater to a [Robert 94i](https://www.robertsradiotechnical.co.uk/productpage.aspx?pid=Stream%2094i) locally (only).

On starting up the container, I get the following PHP error message:

```
Fatal error: Uncaught RedisException: Connection refused in /php-code/classes/RedisCache.php:44 Stack trace: #0 /php-code/classes/RedisCache.php(44): Redis->pconnect('127.0.0.1', 6379) #1 /php-code/classes/Cache.php(131): RedisCache->__construct('allowed_domains') #2 /php-code/classes/Config.php(143): Cache->__construct('allowed_domains') #3 /php-code/classes/Login.php(20): Config::checkAccess() #4 /php-code/gui/index.php(18): Login->__construct() #5 {main} thrown in /php-code/classes/RedisCache.php on line 44
```

```
[~] # docker logs 1bab3a4b530d

Fatal error: Uncaught RedisException: Connection refused in /php-code/classes/RedisCache.php:44
Stack trace:
#0 /php-code/classes/RedisCache.php(44): Redis->pconnect('127.0.0.1', 6379)
#1 /php-code/classes/Cache.php(131): RedisCache->__construct('allowed_domains')
#2 /php-code/classes/Config.php(250): Cache->__construct('allowed_domains')
#3 /startup.php(24): Config::parseAllowedDomain(true)
#4 {main}
  thrown in /php-code/classes/RedisCache.php on line 44
[21-Jan-2024 18:06:41] NOTICE: fpm is running, pid 15
[21-Jan-2024 18:06:41] NOTICE: ready to handle connections
127.0.0.1 -  21/Jan/2024:18:07:11 +0000 "GET /index.php" 200
127.0.0.1 -  21/Jan/2024:18:07:13 +0000 "GET /gui/index.php" 200
```

## Environment variables

| Key  | Value |
| ------------- | ------------- |
| CONF_ALLOWED_DOMAIN | all |
| CONF_CACHE_EXPIRE | 1200 |
| CONF_DOMAIN | http://192.168.2.51 |
| CONF_LOG_DIR | /php-code/data |
| CONF_SHUFFLE_MUSIC | true |
| DEV | dev |
| DOCKER_MODE | true |
| GPG_KEYS | 1198C0117593497A5EC5C199286AF1F9897469DC C28D937575603EB4ABB725861C0779DC5C0A9DE4A FD8691FDAEDF03BDF6E460563F15A9B715376CA| 
| PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |
| PHPIZE_DEPS | autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c |
| PHP_ASC_URL | https://www.php.net/distributions/php-8.3.1.tar.xz.asc |
| PHP_CFLAGS | -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 |
| PHP_CPPFLAGS | -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 |
| PHP_INI_DIR | /usr/local/etc/php |
| PHP_LDFLAGS | -Wl,-O1 -pie |
| PHP_SHA256 | 56445b1771b2ba5b7573453f9e8a9451e2d810b1741a352fa05259733b1e9758 |
| PHP_URL | https://www.php.net/distributions/php-8.3.1.tar.xz |
| PHP_VERSION | 8.3.1 |

## Troubleshooting

1. `http://192.168.2.51/setupapp/iden/asp/BrowseXML/loginXML.asp?token=0`  → Success
2.  `http://192.168.2.51/setupapp/iden/asp/BrowseXML/loginXML.asp?gofile=&mac=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&dlang=eng&fver=4&ven=iden00` → Failure
3. Get the GUI-Code from the preceding response and try to used it to access the GUI at http://192.168.2.51/gui/ → Failure

Despite the `CONF_LOG_DIR` variable, I do not see any kind of log file in `/php-code/data` directory, only the radio files:   
```
/php-code/data # ls -la
total 24
drwxrwxrwx    2 www-data www-data      4096 Jan 21 02:37 .
drwxr-xr-x    1 root     root          4096 Dec 31 04:27 ..
-rw-r--r--    1 www-data www-data       694 Dec 31 04:28 env.json
-rw-r--r--    1 www-data www-data       218 Jan 21 02:00 my_stations.json
-rw-r--r--    1 www-data www-data         3 Dec 31 04:28 podcasts_1.json
-rw-r--r--    1 www-data www-data       215 Dec 31 04:28 radios_1.json
```

There is no content in `/var/log/nginx/error.log`:   
```
var/log/nginx # cat error.log 
/var/log/nginx # 
```

The shell on the container itself does not provide much useful output:   
```
/php-code # nc 127.0.0.1 6379
/php-code # nc 192.168.2.51 6379
/php-code # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 sh /startup.sh
   10 root      0:00 nginx: master process nginx -g pid /tmp/nginx.pid;
   11 www-data  0:00 nginx: worker process
   12 www-data  0:00 nginx: worker process
   13 www-data  0:00 nginx: worker process
   14 www-data  0:00 nginx: worker process
   15 root      0:00 php-fpm: master process (/usr/local/etc/php-fpm.conf)
   16 www-data  0:00 php-fpm: pool www
   17 www-data  0:00 php-fpm: pool www
   25 root      0:00 /bin/sh
   32 root      0:00 /bin/sh
   42 root      0:00 ps -ef
```

From `ps`, I get this impression Redis is simply not running. Is Redis supposed to come part of the container, or is there an implicit expectation that the host runs a Redis instance?   
How can I continue troubleshooting this issue?

**Comment by kimbtech** [comment]
Hi,
Redis needs to be started in a separate Docker container. This is e.g. done by the [docker-compose.yml](https://github.com/KIMB-technologies/Radio-API/blob/master/docker-compose.yml#L27).

If using this docker-compose.yml the Redis service is available with the hostname `redis` (thus, `CONF_REDIS_HOST=redis`).

**Comment by SpeedyGoneZales** [comment]
Cool, I've got it kinda working now.   
Many thanks for providing this solution, much appreciated!
