### ISSUE TITLE
Characters with diacritics are stripped

### ISSUE THREAD

**Issue by SpeedyGoneZales** [KIMB-technologies/Radio-API#47]
**Describe the Bug**  
After saving as a user-defined stream `BBC Radio nan Gàidheal`, the `à` is stripped and only `BBC Radio nan Gidheal` remains.   
Also an issue for stations by the Austrian broadcaster Österreichischer Rundfunk, e.g. `Ö1`.

**To Reproduce**  
1. Go to /gui
2. In `Name` enter a character with a diacritic
3. Press save
4. Reload the page. The character has disappeared.

**Radio-API Installation**
- Version of Radio-API: 2.8.0
- Installation mode: Docker
- DNS redirect via: Router
- Radio vendor: Roberts
- Usage of reverse proxy:  no

**Comment by kimbtech** [comment]
Hi,
I just pushed an update with less strict character replacement/ stripping. All textual characters should now be allowed, while emojis and similar are still not allowed.

Some characters like `<`, `>`, or `&` are still not displayed on the radio. (The radio uses XML, but it seems to not support common techniques for escaping these characters. At least I did not find the supported techniques.)

**Comment by SpeedyGoneZales** [comment]
Nice, thank you!
