### ISSUE TITLE
Does this software require redis dependency to function?

### ISSUE THREAD

**Issue by fletchg** [KIMB-technologies/Radio-API#49]
Hello

For several days I have been attempting  to install this software with mixed results. Bottom line it passses your first test - getting the token but that is about it. I have been able to fix all errors except the one getting access denied by redis:

<html>
<body>

2024/02/24 21:09:23 | stdout | thrown in /php-code/classes/RedisCache.php on line 44
-- | -- | --
2024/02/24 21:09:23 | stdout | #4 {main}
2024/02/24 21:09:23 | stdout | #3 /startup.php(24): Config::parseAllowedDomain(true)
2024/02/24 21:09:23 | stdout | #2 /php-code/classes/Config.php(250): Cache->__construct('allowed_domains')
2024/02/24 21:09:23 | stdout | #1 /php-code/classes/Cache.php(131): RedisCache->__construct('allowed_domains')
2024/02/24 21:09:23 | stdout | #0 /php-code/classes/RedisCache.php(44): Redis->pconnect('127.0.0.1', 6379)
2024/02/24 21:09:23 | stdout | Stack trace:
2024/02/24 21:09:23 | stdout | Fatal error: Uncaught RedisException: Connection refused in /php-code/classes/RedisCache.php:44

</body>
</html>

I am I supposed to run another docker with redis? I have tried that with same results. Even if Frontier doesn't pull the plug in March, I would still like this for my sangean. Thank you.

**Comment by kimbtech** [comment]
Hi,

the Docker container  of Radio-API requires to run another container with redis.

I seems that `CONF_REDIS_HOST` is empty or `127.0.0.1` in your config, what will be the Docker container running Radio-API itself, but not redis. The value of `CONF_REDIS_HOST` should be a (possibly local) host name of the redis container.

If you use [this](https://github.com/KIMB-technologies/Radio-API/blob/master/docker-compose.yml) Docker compose file, redis will get the hostname `redis`. Otherwise you may create a network using Docker for both containers and use the hostname/ ip of redis in this network.

**Comment by fletchg** [comment]
Ok if I understand correctly:
I need to run a separate container running redis.

I need to define CONF_REDIS_HOST with the hostname from the redis docker?
Can I use IP instead of host name?

Thanks!, Fletch

**Comment by kimbtech** [comment]
Hi,

yes, you need two containers and set `CONF_REDIS_HOST` to the redis hostname.
The example docker-compose.yml will automatically start both required containers. It then should work with the default hostname `redis`.

Yes, an IP address may be also used, but make sure, that the IP address is reachable by the Radio-API container. (And Docker IP addresses may not be stable after restarts.)

**Comment by fletchg** [comment]
I am getting closer. I tried using a hostname and the IP and still
getting errors but not the same:
2024/02/25 19:34:13 stdout Stack trace:
2024/02/25 19:34:13 stdout
Fatal error: Uncaught RedisException: php_network_getaddresses:
getaddrinfo for redis failed: Name has no usable address in
/php-code/classes/RedisCache.php:44
2024/02/25 19:34:13 stdout
2024/02/25 19:34:13 stdout
Warning: Redis::pconnect(): php_network_getaddresses: getaddrinfo for
redis failed: Name has no usable address in
/php-code/classes/RedisCache.php on line 44
2024/02/25 19:34:13 stdout
2024/02/25 19:30:55 stdout
127.0.0.1 -  26/Feb/2024:01:30:55 +0000 "GET /index.php" 200
2024/02/25 19:30:42 stdout
127.0.0.1 -  26/Feb/2024:01:30:42 +0000 "GET /index.php" 200
2024/02/25 19:28:24 stdout
[26-Feb-2024 01:28:24] NOTICE: ready to handle connections
2024/02/25 19:28:24 stdout
[26-Feb-2024 01:28:24] NOTICE: fpm is running, pid 19
2024/02/25 19:28:24 stdout
  thrown in /php-code/classes/RedisCache.php on line 44
2024/02/25 19:28:24 stdout #4 {main}
2024/02/25 19:28:24 stdout
#3 /startup.php(24): Config::parseAllowedDomain(true)
2024/02/25 19:28:24 stdout
#2 /php-code/classes/Config.php(250): Cache->__construct('allowed_domains')
2024/02/25 19:28:24 stdout
#1 /php-code/classes/Cache.php(131): RedisCache->__construct('allowed_domains')
2024/02/25 19:28:24 stdout
#0 /php-code/classes/RedisCache.php(44): Redis->pconnect('redis', 6379)
2024/02/25 19:28:24 stdout Stack trace:
2024/02/25 19:28:24 stdout
Fatal error: Uncaught RedisException: php_network_getaddresses:
getaddrinfo for redis failed: Name has no usable address in
/php-code/classes/RedisCache.php:44
2024/02/25 19:28:24 stdout
2024/02/25 19:28:24 stdout
Warning: Redis::pconnect(): php_network_getaddresses: getaddrinfo for
redis failed: Name has no usable address in
/php-code/classes/RedisCache.php on line 44
2024/02/25 19:28:24 stdout



But things are better as the gui now shows up but it won't accept the token
to log in. The token box has a Z in it. Is that normal?

Thank you.

**Comment by kimbtech** [comment]
Hi,

it now looks better, but still seems a bit fiddly with Redis. I have release a new version v2.8.3 which allows to run Radio-API via Docker but without requiring Redis (falling back to a JSON-based cache, just like the manual install). For huge installations the JSON-based cache may be a bit slow, but with one or two radios, it should work well.

Thus, you now can set `CONF_USE_JSON_CACHE=true` in the `environment`-section of `docker-compose.yml`.
Afterwards, no Redis container is needed any more and Radio-API should run.
And make sure to pull the latest version of `kimbtechnologies/radio_api:latest`, e.g., by running `docker-compose pull`.

Yes, the first letter of all tokens (called GUI-Codes is `Z`). This GUI-codes are shown on the radio's display and are used to identify which radio belongs to a user of the WebGUI. 
Thus, when connecting your radio to Radio-API for the first time, you will get a GUI-Code starting with `Z` to log into the WebGUI.

**Comment by reinob** [comment]
I just tested v2.8.3 enabling CONF_USE_JSON_CACHE=true and removing the REDIS-related env vars (I also stopped my redis instance), but then the radio didn't work.

I didn't debug anything so far, but I stopped the container, added the REDIS-related variables again (but left the CONF_USE_JSON_CACHE=true), started the redis server, and everything works again.

Hopefully I'll have time to play with it tomorrow!
Thanks in any case, I would be happy to stop/remove redis from my server.

**Comment by kimbtech** [comment]
I moved the problem when switching from Redis mode to non-Redis mode to a new issue #51.

**Comment by kimbtech** [comment]
Regarding the token:

The token `3a3f5ac48a1dab4e` is a static one and used by the radio to somewhat validate if the server provides the correct API.

You will need to connect your radio to Radio-API once and see a `GUI-Code: Z****` on the radio's display. This GUI-Code can than be used to access the webinterface. (In other words, the radio registers on first connect with the server and then one can use the webinterface to manage stations etc. for this radio.)

**Comment by fletchg** [comment]
Ok good news- finally got this up and going on my synology docker with redis. The issue with the docker-compose.yml file always giving errors turned out to be that I had to declare the data paths.   - ./data/:/php-code/data/ will not work and always gives errors, but -  /volume1/docker/sangean/data/:/php-code/data/ installs just fine. The synlogy pro that helped me said to change - "8080:80" to this - 8080:80 as well but regardless it is up now with zero errors!

Now I could use some help getting the radio connected. I gave it a static IP changed the dns to my docker server 192.168.11.49 but left the gateway at 192.168.11.1. 

I then installed radio.dns and set radio_ip to 192.168.11.49 and set upstream like this : - SERVER_UPSTREAM=192.168.11.1

I then ran it and tried connecting the radio but noticed it connects to wifi fine but can't see the internet nor does it offer me the code/token.

I noticed you did not expose port 53 and figured that needed to be done but no change.  Do my settings look ok?

Thank you.

**Comment by kimbtech** [comment]
Hi,
if I understand it correctly, you use my Radio-DNS Docker container (https://github.com/KIMB-technologies/Radio-DNS-Server/blob/master/docker-compose.yml).

This Docker container uses `network_mode: host ` and thus you do not need to expose a port, as the network of the container is shared with the network of the Synology host itself.

However, you may not set SERVER_UPSTREAM to a local IP. This IP needs to be the IP of an DNS resolver, the default uses Google DNS at `8.8.8.8`, which should work well.

Thus, the full configuration should look for example like this:
```
- SERVER_BIND=0.0.0.0
- SERVER_PORT=53
- SERVER_UPSTREAM=8.8.8.8
- RADIO_IP=192.168.11.49
- ALLOWED_DOMAIN=all
- TIME_SERVER=ntp0.fau.de
```

Afterwards, your radio should be able to connect.

If not, please send the repose from Radio-DNS for „hama.wifiradiofrontier.com“, e.g., this response may be generated by `dig hama.wifiradiofrontier.com @192.168.11.49`.

**Comment by fletchg** [comment]
I am not sure if this will help but here is the docker log showing requests
to radio-dns. The google requests came from me, not the rado. Thank you.

radio_dns
datestreamcontent
2024/02/28 08:04:11 stdout
2024-02-28 14:04:11 [DNSHandler:Resolver] Reply: [192.168.11.171:61998
] (udp) / 'google.com.' (AAAA) / RRs: AAAA,AAAA,AAAA,AAAA
2024/02/28 08:04:11 stdout
2024-02-28 14:04:11 [DNSHandler:Resolver] Request: [192.168.11.171:61998
] (udp) / 'google.com.' (AAAA)
2024/02/28 08:04:11 stdout
2024-02-28 14:04:11 [DNSHandler:Resolver] Reply: [192.168.11.171:61997
] (udp) / 'google.com.' (A) / RRs: A,A,A,A,A,A
2024/02/28 08:04:11 stdout
2024-02-28 14:04:11 [DNSHandler:Resolver] Request: [192.168.11.171:61997
] (udp) / 'google.com.' (A)
2024/02/28 08:04:09 stdout
2024-02-28 14:04:09 [DNSHandler:Resolver] Reply: [192.168.11.171:63375
] (udp) / 'google.com.' (AAAA) / RRs: AAAA,AAAA,AAAA,AAAA
2024/02/28 08:04:09 stdout
2024-02-28 14:04:09 [DNSHandler:Resolver] Request: [192.168.11.171:63375
] (udp) / 'google.com.' (AAAA)
2024/02/28 08:04:09 stdout
2024-02-28 14:04:09 [DNSHandler:Resolver] Reply: [192.168.11.171:63374
] (udp) / 'google.com.' (A) / RRs: A,A,A,A,A,A
2024/02/28 08:04:09 stdout
2024-02-28 14:04:09 [DNSHandler:Resolver] Request: [192.168.11.171:63374
] (udp) / 'google.com.' (A)
2024/02/28 08:04:09 stdout
2024-02-28 14:04:09 [DNSHandler:Resolver] Reply: [192.168.11.170:51095
] (udp) / 'time.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:04:09 stdout
2024-02-28 14:04:09 [DNSHandler:Resolver] Request: [192.168.11.170:51095
] (udp) / 'time.wifiradiofrontier.com.' (A)
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Reply: [192.168.11.170:51109
] (udp) / 'sangean2.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Request: [192.168.11.170:51109
] (udp) / 'sangean2.wifiradiofrontier.com.' (A)
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Reply: [192.168.11.170:51108
] (udp) / 'sangean.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Request: [192.168.11.170:51108
] (udp) / 'sangean.wifiradiofrontier.com.' (A)
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Reply: [192.168.11.170:51107
] (udp) / 'sangean2.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Request: [192.168.11.170:51107
] (udp) / 'sangean2.wifiradiofrontier.com.' (A)
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Reply: [192.168.11.170:51106
] (udp) / 'sangean.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:21 stdout
2024-02-28 14:03:21 [DNSHandler:Resolver] Request: [192.168.11.170:51106
] (udp) / 'sangean.wifiradiofrontier.com.' (A)
2024/02/28 08:03:18 stdout
2024-02-28 14:03:18 [DNSHandler:Resolver] Reply: [192.168.11.170:51105
] (udp) / 'update.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:18 stdout
2024-02-28 14:03:18 [DNSHandler:Resolver] Request: [192.168.11.170:51105
] (udp) / 'update.wifiradiofrontier.com.' (A)
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Reply: [192.168.11.170:51104
] (udp) / 'sangean2.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Request: [192.168.11.170:51104
] (udp) / 'sangean2.wifiradiofrontier.com.' (A)
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Reply: [192.168.11.170:51103
] (udp) / 'sangean.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Request: [192.168.11.170:51103
] (udp) / 'sangean.wifiradiofrontier.com.' (A)
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Reply: [192.168.11.170:51102
] (udp) / 'sangean2.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Request: [192.168.11.170:51102
] (udp) / 'sangean2.wifiradiofrontier.com.' (A)
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Reply: [192.168.11.170:51101
] (udp) / 'sangean.wifiradiofrontier.com.' (A) / RRs: A
2024/02/28 08:03:13 stdout
2024-02-28 14:03:13 [DNSHandler:Resolver] Request: [192.168.11.170:51101
] (udp) / 'sangean.wifiradiofrontier.com.' (A)
2024/02/28 08:03:04 stdout
2024-02-28 14:03:04 [DNSHandler:Resolver] Reply: [192.168.11.171:56292
] (udp) / 'google.com.' (AAAA) / RRs: AAAA,AAAA,AAAA,AAAA

**Comment by kimbtech** [comment]
Hi,
the DNS responses look good and the requests in the log also.

Thus, I assume Radio-DNS works well and the problem is something between the radio and Radio-API.
Do you see request of the radio in the logs of Radio-API? If yes, we are sure that the radio request the right server.

Does the radio show some type of error message?

What is responses of `curl "http://192.168.11.49/setupapp/iden/asp/BrowseXML/loginXML.asp?token=0" -H "Host: sangean.wifiradiofrontier.com"`, it should be `<EncryptedToken>3a3f5ac48a1dab4e</EncryptedToken>`.

Does `curl "http://192.168.11.49/setupapp/iden/asp/BrowseXML/loginXML.asp?gofile=&mac=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&dlang=eng&fver=4&ven=iden00" -H "Host: sangean.wifiradiofrontier.com"` show something like `<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <ListOfItems> ... </ListOfItems>`, including `<Title>GUI-Code: ...</Title>`?

**Comment by fletchg** [comment]
Hello. I think you are right about the issue being between the radio and
Radio-API.. All I see in the logs are me trying to access it from the web
page:
datestreamcontent
2024/02/29 16:38:51 stderr
127.0.0.1 -  29/Feb/2024:22:38:50 +0000 "GET /index.php" 200
2024/02/29 16:36:41 stderr
127.0.0.1 -  29/Feb/2024:22:36:41 +0000 "GET /index.php" 200
2024/02/28 08:22:18 stderr
127.0.0.1 -  28/Feb/2024:14:22:18 +0000 "GET /gui/view.php" 200
2024/02/28 00:25:37 stderr
127.0.0.1 -  28/Feb/2024:06:25:37 +0000 "GET /gui/view.php" 200
2024/02/27 18:52:32 stderr
127.0.0.1 -  28/Feb/2024:00:52:32 +0000 "GET /gui/view.php" 200
2024/02/27 18:52:17 stderr
127.0.0.1 -  28/Feb/2024:00:52:17 +0000 "GET /gui/index.php" 200
2024/02/27 18:52:14 stderr
127.0.0.1 -  28/Feb/2024:00:52:14 +0000 "GET /gui/index.php" 200
2024/02/27 18:52:10 stderr
127.0.0.1 -  28/Feb/2024:00:52:10 +0000 "GET /gui/view.php" 200
2024/02/27 18:52:08 stderr
127.0.0.1 -  28/Feb/2024:00:52:08 +0000 "GET /gui/view.php" 200
2024/02/27 18:49:31 stderr
[28-Feb-2024 00:49:30] NOTICE: ready to handle connections
2024/02/27 18:49:30 stderr
[28-Feb-2024 00:49:30] NOTICE: fpm is running, pid 20
2024/02/27 18:49:29 stdout Load RadioBrowser:
2024/02/27 18:49:29 stdout Load (Un-)Read:
2024/02/27 18:49:29 stdout
2024/02/27 18:49:29 stdout =================================
2024/02/27 18:49:29 stdout type  : all
2024/02/27 18:49:29 stdout ---------------------------------
2024/02/27 18:49:29 stdout Key  : Value
2024/02/27 18:49:29 stdout =================================
2024/02/27 18:33:37 stderr
[28-Feb-2024 00:33:37] NOTICE: ready to handle connections
2024/02/27 18:33:37 stderr
[28-Feb-2024 00:33:37] NOTICE: fpm is running, pid 20
2024/02/27 18:33:36 stdout Load RadioBrowser:
2024/02/27 18:33:36 stdout Load (Un-)Read:
2024/02/27 18:33:36 stdout
2024/02/27 18:33:36 stdout =================================
2024/02/27 18:33:36 stdout type  : all
2024/02/27 18:33:36 stdout ---------------------------------
2024/02/27 18:33:36 stdout Key  : Value


The first 2 entries are when I was doing the tests you requested today.
What should I be seeing here?


As far as the 2 test you wanted me to run, they look fine as far as I can
tell with the exception is the web output is missing the 8080 port I use on
test 2.

Test 1:
$  curl "
http://192.168.11.49:8080/setupapp/iden/asp/BrowseXML/loginXML.asp?token=0"
-H "Host: sangean.wifiradiofrontier.com"
<EncryptedToken>3a3f5ac48a1dab4e</EncryptedToken

Test 2:
$  curl "
http://192.168.11.49:8080/setupapp/iden/asp/BrowseXML/loginXML.asp?token=0"
-H "Host: sangean.wifiradiofrontier.com"
***@***.***:~ $
curl "
http://192.168.11.49:8080/setupapp/iden/asp/BrowseXML/loginXML.asp?gofile=&mac=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&dlang=eng&fver=4&ven=iden00"
-H "Host: sangean.wifiradiofrontier.com"  curl "
http://192.168.11.49:8080/setupapp/iden/asp/BrowseXML/loginXML.asp?gofile=&mac=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&dlang=eng&fver=4&ven=iden00"
-H "Host: sangean.wifiradiofrontier.com"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ListOfItems>
  <ItemCount>4</ItemCount>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Podcast</Title>
    <UrlDir>http://192.168.11.49/list?tid=3</UrlDir>
    <UrlDirBackUp>http://192.168.11.49/list?tid=3</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Radio stations</Title>
    <UrlDir>http://192.168.11.49/list?tid=1</UrlDir>
    <UrlDirBackUp>http://192.168.11.49/list?tid=1</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>Radio-Browser</Title>
    <UrlDir>http://192.168.11.49/radio-browser?by=none&term=none</UrlDir>
    <UrlDirBackUp>http://192.168.11.49/radio-browser?by=none&term=none
</UrlDirBackUp>
  </Item>
  <Item>
    <ItemType>Dir</ItemType>
    <Title>GUI-Code: Z4UIJ</Title>
    <UrlDir>http://192.168.11.49/?go=initial</UrlDir>
    <UrlDirBackUp>http://192.168.11.49/?go=initial</UrlDirBackUp>
  </Item>
</ListOfItems>


Do notice that this output is missing the 8080 port number that I use on
the server. Does the radio have to use port 80?

As far as to what the radio is doing: it just keeps trying to connect to
the last station that was working. The only thing that might be working is
the time as it gets set but that could be from memory- not sure about this.

1) Does radio-api require port 80 for the radio to be able to connect?

2)  Does the radio need a hard reset or should this not be needed?


Thank you!

**Comment by kimbtech** [comment]
Hi,
the logs are very helpful and Radio-API seems to run fine.
However, the radio always requests port 80 to access the API. Thus, you should change the port in the docker-compose.yml (or some reverse proxy). (This port configuration in the example was a bit inaccurate, but I just updated it.)

You do not need to do a hard reset.

**Comment by fletchg** [comment]
Hello again,
The port 80 is the issue for sure as Synology has a reverse proxy that
takes port 80 even if not being used . I am looking for a fix for this
right now and if not will move the docker to a linux vm (proxmox).
Thank you for all your help -and the paypal offer still stands for giving
us an alternative for our radios!

**Comment by kimbtech** [comment]
Hi,

this should get Radio-API running, maybe this issue (and the discussion there) might help you: https://github.com/KIMB-technologies/Radio-API/issues/34#issuecomment-1848782797
It is also about using a Synology NAS and its Reverse Proxy.)

**Comment by fletchg** [comment]
I am getting close. Rather than have to fight synology/nginxI port
blocking, I  went ahead and installed a linux vm today under proxmox. GUI
came up right away and it looks much different than what I was seeing on
the synology. This one has some color boarders and the other one did not. I
got the radio code and can log in. Radio can see the api and gets lists
from it but it still will not connect and play. Ironically the gui does
play music now. I have to take a break and will work on it later tonight!

**Comment by kimbtech** [comment]
Hi,
it seems as you did an huge step towards getting it working. 
The Web GUI should look like https://github.com/KIMB-technologies/Radio-API/blob/master/screenshots/Readme.md.

If the streams play in the browser and not in the radio, I would assume some problems with https streams (enable the proxy via Web GUI) or issues with `CONF_DOMAIN` and `CONF_RADIO_DOMAIN`.

**Comment by fletchg** [comment]
If I chose a radio station on the gui- should it play on the radio as well?
That doesn't seem to be working but I was able to pick BBC from the radio
menu and it is playing.

Where do I enable the proxy on the gui? Wait I see it...I have to populate
the DB first and I see the option.
Let me play some more but things are looking better! Thank you.

**Comment by kimbtech** [comment]
Hi,

the Web GUI just provides a preview of radio stations, podcast, ... – you can test it there in the browser/ on the computer, but it will not start the radio or select a station in the radio. 

If BBC plays, the then the tricky part is done :)

**Comment by fletchg** [comment]
Yep it's playing great now- even got a favorite local am oldies station
working !
I may still try to get this working on synology later but as long as I have
it working on a VM I am good.
BTW this was MUCH easier to install on  regular linux compared to synology.
1 hour vs 1 week :)

Thanks again and the paypal offer still stands- as this was a big help -
thank you again!

**Comment by kimbtech** [comment]
Hi,
I am happy that it works now!
Yes, Synology seems to be a bit fiddly, I always use a Linux VM/ Server.

Radio-API was started as project for my personal radio. First it was not planned to publish it, but now I am happy that it is used by others!

**Comment by fletchg** [comment]
Thanks again! Even undok phone app still works. I have already added a
local rock station to radio-browser and everything is  working well.

regards,
Fletch
