### ISSUE TITLE
v2.8.3 with CONF_USE_JSON_CACHE=true errors

### ISSUE THREAD

**Issue by kimbtech** [KIMB-technologies/Radio-API#51]
I just tested v2.8.3 enabling CONF_USE_JSON_CACHE=true and removing the REDIS-related env vars (I also stopped my redis instance), but then the radio didn't work.

I didn't debug anything so far, but I stopped the container, added the REDIS-related variables again (but left the CONF_USE_JSON_CACHE=true), started the redis server, and everything works again.

Hopefully I'll have time to play with it tomorrow!
Thanks in any case, I would be happy to stop/remove redis from my server.

_Originally posted by @reinob in https://github.com/KIMB-technologies/Radio-API/issues/49#issuecomment-1965273428_

**Comment by kimbtech** [comment]
Hi,

I just tested it again and for me it works well when I change my config as described – for both, my testing and my production installation.

Do you set the config value `CONF_CACHE_DIR`? (I do not set it.) 
It defaults to `./data/cache` and this directory will be created by Radio-API to store the cache files there. Thus, I could imagine that there are problems with the file permissions. However, on startup the Docker container tries to fix/ to correct file permissions and owners of the `./data` folder and subfolders.

Summarized, I am looking forward to your results of debugging.

**Comment by kimbtech** [comment]
I would be interesting to know, which cache is used with `CONF_USE_JSON_CACHE=true` beneath the Redis config values. I should be the JSON cache.

You may see this, by the files in `./data/cache` and their *last changed* timestamps.

**Comment by reinob** [comment]
I apologize for the delay, and actually for the bug report, which is NOT (!).

I had mistakenly set CONF_USE_JSON_CACHE to "yes" instead of "true", and somehow I couldn't notice that it was not the same :-/

So the error is (was!) definitely between the computer and the keyboard.
It works beautifully, and I really thank you for this feature, and for Radio-API as a whole!!!!

**Comment by kimbtech** [comment]
Hi,
no problem, I am happy that it works and there is no bug.
