### ISSUE TITLE
Station logo not shown everytime

### ISSUE THREAD

**Issue by Demel75** [KIMB-technologies/Radio-API#53]
On some radio stations the logo is not shown.

1. add e.g. Antenne Bayern
2. play station
3. look logo

Settings:
![image](https://github.com/KIMB-technologies/Radio-API/assets/18624555/6321bfa0-be39-47b0-8491-e4fec7b2ddb3)

In a webbrowser logo is shown (http://www.antenne.de/logos/station-antenne-bayern/apple-touch-icon.png)

On some other station it works:
![image](https://github.com/KIMB-technologies/Radio-API/assets/18624555/a2bd305b-617f-440d-9c5f-80b744361545)

Are png-files not supported?

- Version of Radio-API: 2.84
- Installation mode: Docker
- DNS redirect via: Radio-DNS
- Radio vendor: Revo Pixis
- Usage of reverse proxy: no

**Comment by kimbtech** [comment]
Hi,
as tackin already stated, the links to the logos are send to the radio and the radio requests them itself.
The radio supports png file, but not https, which might be the reason for one logo working and one not:

- `https://www.antenne.de/logos/station-antenne-bayern/apple-touch-icon.png` works, but `http://www.antenne.de/logos/station-antenne-bayern/apple-touch-icon.png` without `s` redirects to the https version.
- `https://cdn-profiles.tunein.com/s25260/images/logod` is also available without `s`, i.e., `http://cdn-profiles.tunein.com/s25260/images/logod`

You may notice, that your links to the logos are using `https` both times, but Radio-API tries to send urls without https to the radio. Thus, the radio gets `http://www.antenne.de/…` and `https://cdn-profiles.tunein.com/…` whereas only one link works.

As solution, Radio-API would need to download the logos and provide them to the radio without requiring https. (Similar to the proxy for streams). However, this is currently not implemented, but might be an *upcoming* feature.

In the meantime, one might manually add the logos to Radio-API:
1. Add the line `- ./media/:/php-code/media/` to the docker-compose `volumes` section. (Not required in non-Docker mode.)
2. Download the missing logos and move them to `./media/` as, e.g., `antenne.png`
3. Set `http://<my-radio-api-server>/media/antenne.png` as station logo.

**Comment by Demel75** [comment]
information submitted later:
This station works with png. 
![image](https://github.com/KIMB-technologies/Radio-API/assets/18624555/68070862-f035-469a-aeb0-7d7f93e7c2fb)

So png support should be there.

**Comment by kimbtech** [comment]
Hi, I just published an update providing an image cache solving the problem of SSL served logos.

**Comment by Demel75** [comment]
:-) Great job. Works like a charm. Thanx
