### ISSUE TITLE
Einstellungen : Reihenfolge ändern

### ISSUE THREAD

**Issue by Sepphuber007** [KIMB-technologies/Radio-API#60]
Hallo, 
kann man die Reihenfolge der 4 unten genannten Punkte ändern:

[Podcast →]
[Radiosender →]
[Radio-Browser →]
[GUI-Code: xxx →]

Wenn es möglich ist würde ich gerne den Radiosender auf Platz 1 haben.

Kann ich das selber wo einstellen ?

Danke im vorraus tolles API

lg Sepp

**Comment by kimbtech** [comment]
Hi,
aktuell ist es nicht möglich, die Sortierung zu verändern. Die Standardeinstellung ist, dass die Elemente nach dem Namen alphabetisch sortiert werden und der GUI-Code ganz unten ist.

Ich könnte darüber nachdenken, ob man Favoriten angeben kann, sodass diese dann oben angezeigt werden.

**Comment by Sepphuber007** [comment]
Hallo,

Danke wäre toll wenn du das mal umsetzen könntest.
Deine Radio API ist toll.

lg Sepp

**Comment by kimbtech** [comment]
Ich habe nun Favoriten auf zwei Arten realisiert:

1. Man kann Sender und Podcasts über das Webinterface einer Kategorie `Favoriten` hinzufügen (einfach Kategorie mit diesen Namen erstellen, falls keine vorhanden). Sofern des Sender mit der Kategorie `Favoriten` gibt, taucht auf oberster Ebene des Radios `Favoriten` auf und listet alle Sender und Podcasts, die in dieser Kategorie sind auf.
2. Man kann über die Konfiguration von Radio-API mit dem Parameter `CONF_FAVORITE_ITEMS` allgemein die Sortierung von Elementen im Radio beeinflussen. Setzt man z.B. `CONF_FAVORITE_ITEMS` auf `Radio,Radio-Browser`, so werden die Einträte mit den Namen `Radio` und `Radio-Browser` weiter oben einsoriert.

**Comment by Sepphuber007** [comment]
Hallo!

Sorry das ich nochmal frage möchte nur das am Radio so angezeigt wird

[Radiosender →]
[Podcast →]
[Radio-Browser →]
[GUI-Code: xxx →]

Habe versucht Favoriten neu alsKategorie anzulegen es steht auch Favoriten ( Changed podcasts! in grün )  aber es ist immer noch Podcast als erster im Radio leider... was mache ich falsch.

verstehe leider nicht wie ich das umsetzen kann bin leider noch anfänger.
Kannst du es mir evtl nochmal schreiben 
Würd mich über deine Hilfe freuen danke im vorraus.

lg
Sepp

**Comment by kimbtech** [comment]
Hallo, 
ich glaube, in diesem  konkreten Fall ist es am einfachsten, wenn über die Konfiguration von Radio-API `CONF_FAVORITE_ITEMS` auf den Wert `Radio` gesetzt wird.
Also entweder `"CONF_FAVORITE_ITEMS" : "Radio",` in der `env.json` hinzugefügt oder `- CONF_FAVORITE_ITEMS=Radio` in der `docker-compose.yml`.

**Comment by Sepphuber007** [comment]
Puh leider kenne ich mich da nicht so gut aus da stehe ich mom an .....

lg Sepp

**Comment by kimbtech** [comment]
Hi,
in der konkreten Installation von Radio-API gibt es ja eine Konfiguration. Bei einer Installation mittels Docker in der `docker-compose.yml`, bei einer *lokalen* Installation in einer Datei `env.json`.

Falls es eine Installation via Docker ist, dann muss die `docker-compose.yml` angepasst werden. Beispiel [hier](https://github.com/KIMB-technologies/Radio-API/blob/master/docker-compose.yml#L27), sodass dort eine Zeile `- CONF_FAVORITE_ITEMS=Radio ` hinzugefügt werden muss und anschließend Radio-API mittels `docker compose up -d` neu gestartet werden muss.

Falls es eine _lokale_ Installation ohne Docker ist, dann muss die Datei `env.json` angepasst werden, die liegt üblicherweise unter `./data/env.json`. Beispiel [hier](https://github.com/KIMB-technologies/Radio-API/blob/master/php/data/env.json#L15), sodass eine Zeile `"CONF_FAVORITE_ITEMS" : "Radio", ` hinzugefügt werden muss. (Ein Neustart ist nicht nötig.)

**Comment by Sepphuber007** [comment]
Danke für deine Erklärung werde es versuchen.
lg Sepp

**Comment by Sepphuber007** [comment]
Update hat funktioniert vielen lieben Dank

lg Sepp
