### ISSUE TITLE
 Radio Api Plugin / Radio Api Redis 

### ISSUE THREAD

**Issue by Sepphuber007** [KIMB-technologies/Radio-API#62]
Hallo Kurze frage kann ich bei Radio Api Plugin auch statt Radio Api Redis das APCu als Caching system 1nehmen ?

lg Sepp

**Comment by kimbtech** [comment]
Hallo,
APCu wird leider nicht unterstützt. Es gibt nur die Wahl zwischen Redis und dem JSON basierten Dateicache (welcher der Standard für eine Installation ohne Docker ist.)

Um Redis abzuschalten und den JSON basierten Dateicache zu aktiveren, muss in der `docker-compose.yml` unter `environment`  der Wert `CONF_USE_JSON_CACHE=true` gesetzt werden. (Der gesamte Teil nach [`depends_on`](https://github.com/KIMB-technologies/Radio-API/blob/master/docker-compose.yml#L28) kann dann entfernt werden.)

Nach einem Neustart des Docker Containers wird der  dann Dateicache dann unter `./data/cache/` angelegt.

Es ist wohl zum empfehlen vor dem Abschalten von Redis ein Backup mit dem [Im- & Export Tool](https://github.com/KIMB-technologies/Radio-API/blob/master/Setup.md#im---export) zu erstellen.

**Comment by Sepphuber007** [comment]
Danke für deine Info
