### ISSUE TITLE
PHP-Proxy für Streaming-Radios ohne eigenen HTTPS-Stack

### ISSUE THREAD

**Issue by tackin** [KIMB-technologies/Radio-API#65]
Mein Radio müsste einen https-Request machen um den Stream zu bekommen, weil jeder http-Request auf genau den Stream zuerst auf https redirected wird und dann auch noch dynamisch an einen Streaming-Dienst ausgelagert wird.
Das Radio hat aber leider keinen https-Stack.

Hier würde der gespeicherte Streaminglink für das Radio dann z.B. lauten:
http://lokaler-radio-api-server.local/proxy/?url=https://radiostation.de/die-streams-nur-als-https-rausrueckt.mp3
Die hinterlegte PHP-Datei /proxy/index.php
muss:
1. den Request weiterleiten nach draußen
2. notfalls auch einen dann eingehenden "redirect" nach z.B. https://dispacher.deliverer.org/radiostation/12345/stream.mp3 intern auflösen.
3. Den Stream samt header an das Radio weitergeben.

Den Proxy könnte man dann auch als Feature in die Radio-API einbinden und mit dem jeweiligen Radio fest verknüpfen.
Dann würde das Radio von der API schon den Streaminglink "http://radio-API-IP/proxy/?url="eigentlicher Link von Radio-Browser.info" bekommen.

**Comment by kimbtech** [comment]
Hi,
eigentlich sollte der Proxy und die EndURL Funktion von Radio-API genau das bereits bieten. Wobei EndURL nur den Umleitungen (mit HTTPS) folgt und annimmt, dass final dann der Link mittels HTTP erreichbar ist. Der Proxy hingegen ruft den finalen Link dann auch mittels HTTPS ab und schreibt ihn für das Radio auf HTTP um.

- Es kann Bugs bei der Installation ohne Docker geben, der Proxy ist dort mittels PHP realisiert und weniger stabil als der Proxy mittels NGINX in Docker.
- Radiosender, die m3u Dateien ausliefern, können Probleme machen, wenn darin dann relative Links oder HTTPs Links genannt sind. (Schwer zu beheben, dann müssen alle M3U-Dateien geparst werden und man müsste M3U vollständig in Radio-API implementieren ... )
- RadioBrowser unterstützt kein EndURL/ Proxy, man kann aber den Link aus Radio-Browser (über-)nehmen und als Radiosender in Radio-API hinterlegen und den Proxy aktivieren.

**Comment by tackin** [comment]
Ich nutze Radio-API ohne Docker, direkt unter apache2 auf dem Raspi und vermute, das ist dann vermutlich eh nicht so "stabil" mit dem Proxy-Dienst.
Ein Stationurl-item mit Proxy ist dann z.B. http://wifiradiofrontier.com/stream.php?id=1001&mac=fe9971xxxxxxyyyyyyy
Der Aufruf davon im Browser liefert mir aber nur "Connection Error".
curl hab ich in PHP aktiviert laut phpinfo().
Dann ist aber bei mir auch schon Ende mit Debugging des Problems.
Ich hatte schon was bei Radio-API über nen Proxy gelesen, aber nicht verstanden wie der nun funktioniert und was der wo macht.

**Comment by kimbtech** [comment]
Ok, das ist dann ja ärgerlich, eigentlich sollte es genau so gehen. Der Link mit stream.php sollte dann die externe URL öffnen und die Daten an das Radio öffnen.

Die Fehlermeldung kommt, wenn der Aufbau der Verbindung zum HTTPS fehlschlägt. Wenn ich den HTTPS Link habe, könnte ich versuchen es zu debuggen.

**Comment by tackin** [comment]
z.B. :
http://liveradio.swr.de/sw282p3/swr3/play.mp3
oder 
https://liveradio.swr.de/sw282p3/swr3/play.mp3

**Comment by kimbtech** [comment]
Hi,
ich habe gerade ein paar kleine Dinge angepasst, nun läuft der Sender bei mit auch über den mittels PHP realisierten Proxy. Ich hoffe, v2.9.3 das löst das Problem.
